### PR TITLE
Pgsql provider patches

### PR DESCRIPTION
**Pull request by chr4**
Trying a new pull-request as a desperation move, as the original https://github.com/opscode-cookbooks/database/pull/48 wasn't merged or declined since over one year :(

This is critical for me, and I suppose for other users, as the database cookbook doesn't allow to set e.g. `REPLICATION` permissions in the `postgresql_database_user` provider.

### CODE REVIEW

**Comment by someara** [comment]
@kisoku can you review this?

**Comment by kisoku** [comment]
Not going to merge this, the functionality the requestor requires was added in database 3.1.0, although the implementation is different.

**Comment by chr4** [comment]
Not everything was implemented. 
It's still not possible to specify `GRANT`s on something else then databases: https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_postgresql_user.rb#L73
Compare my implementation of the `on` attribute: https://github.com/opscode-cookbooks/database/pull/97/files#diff-cd148bd1fe580561c4205335f451fa6aR65

**Comment by chr4** [comment]
As far as I can see statements like `GRANT SELECT on table_c TO readonly` are not possible using the current implementation.

**Comment by chr4** [comment]
I'm raising this again.
Since postgresql-9.4 there are more issues coming up, e.g. creating a replication only user fails, because the cookbook is not using `pg_roles` to check whether a role exists, but `pg_users`. Since `9.4`, a role with `NOLOGIN, REPLICATION` is not listed in `pg_users` therefore raising:

```
PG::DuplicateObject
    -------------------
    ERROR:  role "replication_user" already exists
```

**Comment by chewi** [comment]
I like @chr4's `on` approach as it supports a wide-range of GRANT styles, potentially including future ones, with little code. Contrast this with #92, which is a lot bigger. I need to be able to do `GRANT SELECT ON ALL TABLES IN SCHEMA foo TO bar`. All the other changes look good too, though the `options` stuff doesn't seem needed now. Would a pull request without that part be accepted?

**Comment by chewi** [comment]
I have run into this once again in an entirely different context. :disappointed:

**Comment by chr4** [comment]
I proposed the most ciritical part of this (fixes the issue when creating a `REPLICATION` rule) in another pull-request https://github.com/chef-cookbooks/database/pull/166, just rebased this onto v5.0.0.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.

**Pull request closed without merging**
