### PR TITLE
[COOK-4674] - Verify and update password if user already exists

### PR DESCRIPTION
**Pull request by iartarisi**

### CODE REVIEW

**Comment by eric-tucker** [comment]
Can we merge this please?  I fully expect the create option to change the password if I have to update passwords.  I should be able to just update an attribute in the data bag and run the same recipe to cause the password to be updated.  I shouldn't have to make recipe changes just to update a password.

Thanks!

**Comment by mdgreenfield** [comment]
:+1:

**Comment by pavel-d** [comment]
Any updates on this?

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.

**Pull request closed without merging**
